Legger til endring for CV model
navikt/veilarbmaofs pull request #159
Opened 2020-10-05 16:27 UTC by jjtg-nav

CV-modellen som serveres fra `pam-cv-api` har endret seg, endringene er bakoverkompatible, men fører til at dataer for Autorsasjoner ikke vises korrekt lenger. Denne endringen skal sørge for å oppdatere DTOen som mottas fra APIet slik at dataene vises igjen, dog med nye feltnavn (slik det vises for brukere).

2020-10-06 10:23 UTC, AlexGaard requested changes

2020-10-06 10:23 UTC, AlexGaard commented on src/rest/datatyper/arenaperson.ts
>  	sertifikater: Sertifikat[];
Feltet "sertifikater" kan vel kanskje fjernes siden det ikke brukes lenger. Kan vel også fjerne denne dataen fra mocken.

2020-10-06 10:23 UTC, AlexGaard commented on src/rest/datatyper/arenaperson.ts
> +type AnnenGodkjenning = Sertifikat;
Hadde det vært bedre å rename Sertifikat til Godkjenning siden sertifikater er fjernet?

2020-10-06 10:25 UTC, AlexGaard commented
Supert at du har laget PR for dette :)

2020-10-06 11:30 UTC, jjtg-nav commented on src/rest/datatyper/arenaperson.ts
> +type AnnenGodkjenning = Sertifikat;
Det kan vi godt, da kan den også fjernes fra DTOen i APIet 👍🏽

2020-10-06 11:30 UTC, jjtg-nav commented on src/rest/datatyper/arenaperson.ts
>  	sertifikater: Sertifikat[];
Yupp, kan fjernes, skal endre og pushe committen i løpet av dagen.

2020-10-06 16:20 UTC, jjtg-nav commented
Har gjort endringer som fjerner "sertifikater" helt. 👍🏽

2020-10-07 07:45 UTC, AlexGaard approved these changes

2020-10-08 11:45 UTC, matiasvinjevoll approved these changes

2020-10-08 11:57 UTC, merged