Tk 54 lenke til personforvalteren
navikt/veilarbmaofs pull request #197
Opened 2021-06-28 10:14 UTC by klaramargrethehelgemo

Rettet eslint-feil som stoppet gh-pages og build

2021-06-28 11:04 UTC, AlexGaard requested changes
Tror ikke vi trenger å merge inn alle commitsene på nytt for å fikse lint feilen. Tenker heller å starte en ny branch som kun inneholder fiksen

2021-06-28 11:12 UTC, sneha-d-desai commented on src/components/paneler/innhold/lenkebrukerprofil/lenke-brukerprofil.tsx
> +				<Normaltekst tag="span">Endre personopplysninger</Normaltekst>
Hvorfor bruker vi tag sammen med Normaltekst?

2021-06-28 11:15 UTC, klaramargrethehelgemo commented on src/components/paneler/innhold/lenkebrukerprofil/lenke-brukerprofil.tsx
> +				<Normaltekst tag="span">Endre personopplysninger</Normaltekst>
Det er helt unødendig og jeg tar det bort.

2021-06-29 07:32 UTC, klaramargrethehelgemo commented on src/utils/miljo-utils.ts
> +	return `${finnNavMiljoStreng()}`;
Jeg har startet ny branch TK54-feilretting, og fjernet unødvendig kode og import der. @sneha-d-desai og @AlexGaard skal jeg gjøre det Sneha skriver over?

2021-06-29 07:39 UTC, AlexGaard commented on src/utils/miljo-utils.ts
> +	return `${finnNavMiljoStreng()}`;
Tenker en forenkling kan være greit ja.

Jeg ville kanskje startet med noe slikt:
```
export const NAIS_PREPROD_SUFFIX = 'nais.preprod.local';
export const NAIS_PROD_SUFFIX = 'nais.adeo.no';

export const NAV_INTERN_PREPROD_SUFFIX = 'dev.intern.nav.no';
export const NAV_INTERN_PROD_SUFFIX = 'intern.nav.no';

function isProd(): boolean {
	const host = window.location.host;
	return !host.includes('-');
}

export function finnNaisDomene() {
	return isProd() ? NAIS_PROD_SUFFIX : NAIS_PREPROD_SUFFIX;
}

export function finnInternNavDomene() {
	return isProd() ? NAV_INTERN_PROD_SUFFIX : NAV_INTERN_PREPROD_SUFFIX;
}
```

2021-06-29 07:48 UTC, AlexGaard commented on src/utils/miljo-utils.ts
> +	return `${finnNavMiljoStreng()}`;
Den isProd() sjekken fungerer med de fleste preprod URLene pr i dag, men det vil stoppe å fungere når vi går vekk fra app-q1.adeo.no. 

Et litt mer robust alternativ er f.eks:

```
const DEV_DOMAINS = ['dev', 'app-q1', 'app-q0', 'localhost'];

const erITestMiljo = (): boolean => {
	return window.location.hostname
		.split('.')
		.findIndex(domain => DEV_DOMAINS.includes(domain)) >= 0;
};
```

2021-06-30 10:19 UTC, closed without merging

2021-06-30 10:19 UTC, klaramargrethehelgemo commented
Erstattet av TK54-feilretting