tc-100 nytt designsystem -> knapper
navikt/veilarbmaofs pull request #251
Opened 2022-01-12 12:06 UTC by taniaholst

2022-01-12 13:15 UTC, stianStensli approved these changes

2022-01-12 13:16 UTC, stianStensli requested changes
Denne ser ikke ferdig ut

2022-01-12 14:34 UTC, taniaholst commented
Fææærdiiiig

2022-02-08 11:36 UTC, taniaholst commented
FÆRDIG 4 REALSIEZZZ

2022-12-30 10:55 UTC, tu55eladd commented
Denne ser ferdig ut, bare å merge?

2023-02-03 14:03 UTC, Mathiamu commented
Løst av #327

2023-02-03 14:03 UTC, closed without merging